### ISSUE TITLE
1.22-2.3 test curl cannot find designated file

### ISSUE THREAD

**Issue by mfeblowitz** [Andarius/nginx-upload#2]

**Comment by Andarius** [comment]
Hey @mfeblowitz, can you try the updated README.md and tell me if it works?

**Comment by mfeblowitz** [comment]
Well, not really. Configures and ends with `/docker-entrypoint.sh: Configuration complete; ready for start up` and hangs.

Also, I'm trying the use a combination of to configs (maybe): the regular nginx.conf plus a config that came from a `sites-enabled` extra configuration, with a new `server` entry. 

I tried to use the repo's `nginx.config` and the other config in 2 -v statements, and  it hangs too:

```
docker run --rm   -p 5050:5050 -v  "$(pwd)/cefas-nginx-docker.conf:/etc/nginx/conf.d/cefas-nginx-docker.conf:ro" -v  "$(pwd)/nginx.conf:/etc/nginx/nginx.conf:ro"  --name nginx-upload nginx-upload:dev
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
```

I had to comment out the buffer size directive - ` upload_buffer_size 10M;` - but that's the only complaint I saw.

Suggestions?

**Comment by mfeblowitz** [comment]
Yes, it works
