### ISSUE TITLE
Overriding default configs

### ISSUE THREAD

**Issue by mfeblowitz** [Andarius/nginx-upload#5]
With the COPY directives removed from Dockerfile, what mechanism is used to override the example configs to provide, e.g., accessing post-upload request processing?

**Comment by Andarius** [comment]
You can use the volume mapping as described in the README.md: 

```sh
docker run --rm \
  -p 5050:5050 \
  -v "$(pwd)/nginx.conf:/etc/nginx/nginx.conf:ro" \   <= this line
  --name nginx-upload nginx-upload:dev
  ```
