### ISSUE TITLE
The project license

### ISSUE THREAD

**Issue by Felixoid** [Andarius/nginx-upload#8]
Hello. I'd like to borrow a part of your code and change it for the pipelines, but your project doesn't have a license.

Do you mind adding a license file, so it would be clear how safe it is from that perspective?

**Comment by Andarius** [comment]
Hey @Felixoid, I added the [LICENSE](https://github.com/Andarius/nginx-upload/blob/master/LICENSE) file as requested :).

**Comment by Felixoid** [comment]
Thanks a lot, much appreciated!
